homepage:
  path: /
  methods: [GET]
  controller: App\Controller\HomepageController
  host: 127.0.0.1
contact:
  path: /contact
  methods: [GET]
  controller: App\Controller\ContactController:index
  host: 127.0.0.1
contact_json:
  path: /contact.json
  methods: [GET]
  controller: App\Controller\ContactController:asJson
  host: 127.0.0.1
products:
  path: /produits
  methods: [GET]
  controller: App\Controller\ProductListController:index
  host: 127.0.0.1
tax_rate_new:
  path: /taxe
  methods: [GET,POST]
  controller: App\Controller\TaxRateTypeController:create
  host: 127.0.0.1
tax_rate_edit:
  path: /taxe/{id}
  methods: [GET,PATCH]
  controller: App\Controller\TaxRateTypeController:edit
  host: 127.0.0.1
  requirements:
    id: '\d+'
product_new:
  path: /produit
  methods: [GET,POST]
  controller: App\Controller\ProductTypeController:create
  host: 127.0.0.1
product_edit:
  path: /produit/{id}
  methods: [GET,PATCH]
  controller: App\Controller\ProductTypeController:edit
  host: 127.0.0.1
api_get_product:
  path: /api/produit/{id}
  methods: [GET]
  controller: App\Controller\ApiController:getProduct
  host: 127.0.0.1
api_get_products:
  path: /api/produit/
  methods: [GET]
  controller: App\Controller\ApiController:getProducts
  host: 127.0.0.1